name: iwrqk
description: Unofficial Iwara Flutter Client.

publish_to: 'none'

version: 1.1.0-beta

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  package_info_plus: ^3.1.2
  intl: ^0.18.0
  logger: ^1.3.0
  get_storage: ^2.1.1
  flutter_slidable: ^3.0.0
  flutter_launcher_icons: any
  font_awesome_flutter: ^10.4.0
  get: ^4.6.5
  dio: ^5.1.2
  crypto: ^3.0.3
  queue: ^3.1.0+2
  cached_network_image: ^3.2.3
  keframe: ^3.0.0
  extended_nested_scroll_view: ^6.1.0
  auto_size_text: ^3.0.0
  flutter_secure_storage: ^8.0.0
  oktoast: ^3.3.1
  better_player: ^0.0.83
  local_auth: ^2.1.6
  local_auth_android: ^1.0.28
  local_auth_ios: ^1.1.3
  background_downloader: ^7.1.0
  path_provider: ^2.0.14
  path: ^1.8.2
  open_file: ^3.3.2
  permission_handler: ^10.2.0
  photo_view: ^0.14.0
  flutter_markdown: ^0.6.14
  share_plus: ^6.3.1
  url_launcher: ^6.1.11

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  generate: true
  uses-material-design: false
  assets:
    - assets/app_icon.png

flutter_icons:
  ios: true
  android: true
  image_path_ios: "assets/launcher/ios.png"
  image_path_android: "assets/launcher/android.png"
  adaptive_icon_background: "assets/launcher/background.png"
  adaptive_icon_foreground: "assets/launcher/foreground.png"
